all:
	  g++ -o labclient 32main.cpp 32main.h commands.cpp commands.h core.cpp core.h networking.cpp networkingclient.cpp networkingserver.cpp networking.h utils.cpp utils.h inputcontrol.cpp inputcontrol.h fileTransfer.cpp fileTransfer.h -lcrypto -lX11 -luuid -lpthread -std=c++11
clean:
	$(RM) labclient
	$(RM) labclient.g.gch
